---

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0744'
  notify:
    - Restart HAProxy service

- name: Ensure HAProxy is running and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Install the prometheus-haproxy-exporter package
  ansible.builtin.apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Configure prometheus-haproxy-exporter scrape URI
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-haproxy-exporter
    regexp: '^ARGS='
    line: 'ARGS="--haproxy.scrape-uri=http://localhost:9188/stats;csv"'
  notify: Restart prometheus-haproxy-exporter

- name: Ensure prometheus-haproxy-exporter service is running
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: true
