- name: Add Grafana APT key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: latest

- name: Copy the grafana.ini file to remote host
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  become: yes
  notify: Restart Grafana if configuration changes

- name: Enable and start Grafana service
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: started

#Precreating the dashboard and user for grafana
- name: Copy datasource.yaml
  ansible.builtin.template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: Restart Grafana if configuration changes

- name: Copy main.json
  ansible.builtin.copy:
    src: main.json
    dest: /etc/grafana/provisioning/dashboards/
  notify: Restart Grafana if configuration changes

- name: Copy syslog.json
  ansible.builtin.copy:
    src: syslog.json
    dest: /etc/grafana/provisioning/dashboards/
  notify: Restart Grafana if configuration changes

- name: Copy backups.json
  ansible.builtin.copy:
    src: backups.json
    dest: /etc/grafana/provisioning/dashboards/
  notify: Restart Grafana if configuration changes

- name: Copy backups.json
  ansible.builtin.copy:
    src: mysql.json
    dest: /etc/grafana/provisioning/dashboards/
  notify: Restart Grafana if configuration changes

- name: Copy dashboard.yaml
  ansible.builtin.template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart Grafana if configuration changes
