- name: Ensure uWSGI packages are installed
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: Copy uWSGI configuration for AGAMA application
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: '0600'
  no_log: true
  notify: Restart uWSGI if there is a configuration change

- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
