{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last InfluxDB backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Kryptograafia\", service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of full and incremental InfluxDB backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Kryptograafia\", service=\"influxdb\", type=\"full\"}",
     "legendFormat": "{{service}},{{type}}"
    },
    {
     "expr": "backups_total{user=\"Kryptograafia\", service=\"influxdb\", type=\"incremental\"}",
     "legendFormat": "{{service}},{{type}}"
    }
   ]
  },
  {
   "title": "Time since last MySQL backup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_success_time{user=\"Kryptograafia\", service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of MySQL Full and Incremental Backups:",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Kryptograafia\", service=\"mysql\", type=\"full\"}",
     "legendFormat": "{{service}}, {{type}}"
    },
    {
     "expr": "backups_total{user=\"Kryptograafia\", service=\"mysql\", type=\"incremental\"}\r\n",
     "legendFormat": "{{service}}, {{type}}"
    }
   ]
  }
 ]
}