{
 "title": "Main dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Container status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (node_memory_MemAvailable_bytes) / avg by(instance) (node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "influxdb_write_write_ok", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nr. of items in database of db-1(primary)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"items\") FROM \"agama-stats\" WHERE \"name\" = 'Kryptograafia-1.kryptograafia.io.'"
    }
   ]
  },
  {
   "title": "Amount of A DNS Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(bind_resolver_queries_total{type=\"A\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Item Counts Over Time for All Agamas",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "SELECT \"items\" FROM \"agama-stats\""
    }
   ]
  },
  {
   "title": "NGINX Amount of http Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Amount of Selects per Minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}