---
- name: Create /opt/agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    #mode: '0755'

- name: Download Agama and Dockerfile
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/opt/agama/{{ item.split('/')[-1] }}"
  loop:
    - "https://raw.githubusercontent.com/hudolejev/agama/master/agama.py"
    - "https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile"

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
    state: present

- name: Run Agama container
  community.docker.docker_container:
    name: agama
    image: agama
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    volumes:
      - "/opt/agama:/opt/agama"
  no_log: true
