- name: Install Bind9 service
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Stop and disable systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Update the resolv file
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all'] }}"
  run_once: true

- name: Ensure Bind9 is started and enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

### Bind exporter
- name: Download Bind9 exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus-community/bind_exporter/releases/download/v0.6.1/bind_exporter-0.6.1.linux-amd64.tar.gz
    dest: /tmp/bind_exporter.tar.gz  # Temporary destination on the managed host

- name: Install Bind9 exporter
  ansible.builtin.unarchive:
    src: /tmp/bind_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copy the system definition to /etc/systemd/system/
  ansible.builtin.template:
    src: service_def.j2
    dest: /etc/systemd/system/bind_exporter.service
  notify: Reload systemd to apply changes
#- name: Reload systemd to apply changes
 # ansible.builtin.command: systemctl daemon-reload

- name: Start and enable Bind9 exporter service
  ansible.builtin.systemd:
    name: bind_exporter
    state: started
    enabled: yes

- name: Copy the bind DNS named and local configuration to VM2
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  notify: Restart bind if there is a configuration change

- name: Create master zone file and copy it to VM2
  ansible.builtin.template:
    src: db.kryptograafia.io.j2
    dest: /var/cache/bind/db.{{ startup_name }}
    owner: bind
    group: bind
    mode: '0644'
  notify:
    -  Reload DNS zone file
    -  Restart bind if there is a configuration change
