#- name: Ansible ping module
#  ansible.builtin.ping:

#Limit the apt update to once a day

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: present
  become: true

- name: Install Prometheus node exporter on all VM-s
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Configure rsyslog.conf file
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: Restart rsyslog

- name: Configure rsyslog to send logs to Telegraf
  ansible.builtin.copy:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog
#"*.* @127.0.0.1:1514"
#Configure the users

#- name: Create user juri
 # ansible.builtin.user:
  #  name: juri

#- name: Create user roman
 # ansible.builtin.user:
  #  name: roman

#Configure the ssh keys for remote access

#- name: Configure the ssh public key for juri
 # ansible.posix.authorized_key:
  #  user: juri
   # key: https://github.com/hudolejev.keys

#- name: Configure the ssh public key for roman
 # ansible.posix.authorized_key:
  #  user: roman
   # key: https://github.com/romankuchin.keys
