#- name: Ansible ping module
#  ansible.builtin.ping:

#Limit the apt update to once a day

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: present
  become: true

- name: Ensure pip3 is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Ensure dnspython library is installed on the managed host
  ansible.builtin.pip:
    name: dnspython
    state: present

- name: Install Prometheus node exporter on all VM-s
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Ensure Prometheus Node Exporter service is enabled and started
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started

- name: Configure rsyslog.conf file
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: Restart rsyslog

- name: Configure rsyslog to send logs to Telegraf
  ansible.builtin.copy:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Ensure the backup user exists
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    create_home: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
  become: true
  no_log: true

- name: Add backup server SSH key to known_hosts for user backup
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0644'
  become: true
  no_log: true

- name: Ensure /home/backup/restore directory exists
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0755'

- name: Install Duplicity backup software
  ansible.builtin.apt:
    name: duplicity
    state: present
